### ISSUE TITLE
Feature: Cleartype font smoothing for search widget

### ISSUE THREAD

**Issue by cpkio** [jjw24/Wox#108]
WOX does not use Cleartype for font smoothing in its main search widget, which makes text look dirty, especially on small sizes. Please look into this problem.

**Comment by katchy3132** [comment]
the search text in your fork looks different from the original Wox 1.3.578 - is that due to this issue ? As far as I can tell font settings are the same

![image](https://user-images.githubusercontent.com/3707138/76689334-8b0acb00-663d-11ea-8289-d80a0cf583c3.png)
![image](https://user-images.githubusercontent.com/3707138/76689338-94943300-663d-11ea-9948-273157e37452.png)

**Comment by jjw24** [comment]
> the search text in your fork looks different from the original Wox 1.3.578 - is that due to this issue ? As far as I can tell font settings are the same

I don't believe so. We haven't change the font in the search and cleartype is not enabled on original or this one, but I wonder if this is due to query search result highlighting? @SysC0mp would you know if it's due to highlighting?

**Comment by jjw24** [comment]
Hi @cpkio hope you are well. ClearType has been added to Wox, please help test it if you can by downloading it [here](https://github.com/jjw24/Wox/releases/tag/JJW24-v1.52.23). Once good, please let me know here and I will make it an official release.

**Comment by cpkio** [comment]
Hi @jjw24, I'm well. Hope you're well too. I've tested this release and it looks nice to me. Great job.

**Comment by jjw24** [comment]
> Hi @jjw24, I'm well. Hope you're well too. I've tested this release and it looks nice to me. Great job.

Thank you for your help. I will make this into official release.

Cheers
