### ISSUE TITLE
Wox website has been down for awhile, wondering if you have a solution?

### ISSUE THREAD

**Issue by pesschap** [jjw24/Wox#151]
### Are you submitting a bug report?

No

As the title mentions, Wox website has been down for a while and users are unable to get plugins through the 'wpm install' command. Is there an alternative method to getting these plugins?

**Comment by jjw24** [comment]
The website is down for everyone, which also hosts the plugins I believe. There is already an [issue](https://github.com/Wox-launcher/Wox/issues/2738) created for it so will wait until after the weekend to see upstream authors' response.

Hopefully worst case scenario is that we are able to extract all the hosted plugins and rehost it with the site somewhere else, otherwise will have to resort to reuploading the actively used plugins.

**Comment by jjw24** [comment]
Plugins are available again. Site's back up.
