### ISSUE TITLE
QuerySearchPrecision setting is not saved

### ISSUE THREAD

**Issue by jjw24** [jjw24/Wox#158]
QuerySearchPrecision setting is not saved to user data location's settings file anymore

**Comment by pc223** [comment]
I think it's because of this line, `StringMatcher.Instance` is null sometimes, I caught this exception in the log some time ago, the exception happens when Wox is starting up.

```
StringMatcher.Instance.UserSettingSearchPrecision = precisionScore;
```
https://github.com/jjw24/Wox/blob/f325674d10cb6887c40bbfbfde20a03c1f6e4488/Wox.Infrastructure/UserSettings/Settings.cs#L44

**Comment by jjw24** [comment]
Just going to close this as this repo is no longer maintained, feel free to open the issue in Flow if this is still a problem
