### ISSUE TITLE
New Feature: Update Wox using channel bottom

### ISSUE THREAD

**Issue by HsunGong** [jjw24/Wox#93]
Using `update channel` in https://github.com/Wox-launcher/Wox/blob/13e6c5eefcc669b9abc93d84b569226afe679e9f/Wox.Core/Updater.cs#L93

**Comment by jjw24** [comment]
One thing to be wary of at the moment with this feature is since portable mode has rolled out, the updater needs to cater for it. This is because the Wox installer at the moment wipes out all files in the Wox folder when it runs, so need to have a way to preserve the UserData folder, otherwise user settings are lost in portable mode when update is run. Just thought I note it here for whoever would like to add this feature.

As stated in issue https://github.com/jjw24/Wox/issues/33
